import dayjs from "dayjs";
const columns = [
    {
      title: "时间",
      dataIndex: "createTime",
      ellipsis: true,
      width: 160,
      render: (text) => {
        const timeStr = text ? dayjs(text).format("YYYY-MM-DD HH:mm:ss") : "";
        return timeStr;
      },
      key:0
    },
    {
      title: "日志说明",
      dataIndex: "eventType",
      ellipsis: true,
      width: 120,
      key:1
    },
    {
      title: "级别",
      dataIndex: "eventLevel",
      width: 100,
      key:2
    },
    {
      title: "日志归类",
      dataIndex: "logClassify",
      ellipsis: true,
      width: 150,
      key:3
    },
    {
      title: "日志信息",
      dataIndex: "eventMessage",
      ellipsis: true,
      width: 180,
      key:4
    },
    {
      title: "模块名称",
      dataIndex: "module",
      ellipsis: true,
      width: 120,
      key:5
    },
    {
      title: "操作账号",
      dataIndex: "userName",
      width: 150,
      ellipsis: true,
      key:6
    },
    {
      title: "操作IP",
      dataIndex: "ip",
      width: 100,
      key:7
    },
  ];
  let audData = [
    {
      id: 49,
      createTime: 1702607488777,
      creator: null,
      eventType: "用户登录成功",
      module: "用户认证",
      eventLevel: "通知",
      eventLevelCode: 5,
      eventMessage:
        "The user succeeded in logging in to . (UserType=HTTP, UserName=sysadmin, AuthenticationMethod=-, Ip=127.0.0.1.",
      logClassify: "登录日志",
      userName: "sysadmin",
      ip: "127.0.0.1",
      brief: "LOGIN",
    },
    {
      id: 39,
      createTime: 1702606623313,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "信息",
      eventLevelCode: "6",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "配置日志",
      userName: null,
      ip: null,
      brief: null,
    },
    {
      id: 27,
      createTime: 1702519520282,
      creator: null,
      eventType: "用户登录成功",
      module: "用户认证",
      eventLevel: "通知",
      eventLevelCode: "5",
      eventMessage:
        "The user succeeded in logging in to . (UserType=HTTP], UserName=sysadmin, AuthenticationMethod=-, Ip=127.0.0.1.",
      logClassify: "登录日志",
      userName: "sysadmin",
      ip: "127.0.0.1",
      brief: "LOGIN",
    },
    {
      id: 1,
      createTime: 1701672754192,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "错误",
      eventLevelCode: "3",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "系统日志",
      userName: null,
      ip: null,
      brief: null,
    },
    {
      id: 47,
      createTime: 1701672754192,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "错误",
      eventLevelCode: "3",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "配置日志",
      userName: null,
      ip: null,
      brief: null,
    },
    {
      id: 58,
      createTime: 1701672754192,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "警包",
      eventLevelCode: "1",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "登录日志",
      userName: null,
      ip: null,
      brief: null,
    },
    {
      id: 74,
      createTime: 1701672754192,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "警告",
      eventLevelCode: "4",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "登录日志",
      userName: null,
      ip: null,
      brief: null,
    },
    {
      id: 75,
      createTime: 1701672754192,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "紧急",
      eventLevelCode: "0",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "系统日志",
      userName: null,
      ip: null,
      brief: null,
    },
    {
      id: 89,
      createTime: 1701672754192,
      creator: null,
      eventType: "登录成功",
      module: "登录",
      eventLevel: "严重",
      eventLevelCode: "2",
      eventMessage: "用户登录成功，账号是：sysadmin",
      logClassify: "系统日志",
      userName: null,
      ip: null,
      brief: null,
    },
  ];
  export { columns, audData }